extends SceneTree
## Headless test runner (no addon, blueprint D5).
## Run: godot --headless --path . --script res://tests/run_tests.gd   (exit code 0 = all pass)
## The rules tests replay tests/vectors/cases.json, generated by tools/gen_vectors.py from the Python reference model
## (every expected number there was hand-checked), so this proves the GDScript code matches the verified rules.

const SaveIO := preload("res://src/core/save_io.gd")
const SettingsStore := preload("res://src/core/settings_store.gd")
const ProfileData := preload("res://src/core/profile_data.gd")
const LoadoutData := preload("res://src/core/loadout_data.gd")
const Validator := preload("res://src/core/loadout_validator.gd")
const HudLayout := preload("res://src/core/hud_layout.gd")
const HapticConfig := preload("res://src/core/haptic_config.gd")
const ControlsData := preload("res://src/core/controls_data.gd")
const Combatant := preload("res://src/combat/combatant.gd")
const DamagePipeline := preload("res://src/combat/damage_pipeline.gd")
const Vitals := preload("res://src/combat/vitals.gd")
const SkillExec := preload("res://src/combat/skill_exec.gd")
const StatResolver := preload("res://src/combat/stat_resolver.gd")
const Authority := preload("res://src/net/authority.gd")

var _fails: int = 0
var _passes: int = 0
var _d: Dictionary = {}
var _reg = null
var _vec: Dictionary = {}

func check(cond: bool, msg: String) -> void:
	if cond:
		_passes += 1
	else:
		_fails += 1
		printerr("FAIL: " + msg)

func _near(a: Variant, b: Variant, e: float = 0.0001) -> bool:
	return absf(float(a) - float(b)) <= e

func _same(got: Variant, expected: Variant, label: String) -> void:
	if typeof(expected) == TYPE_BOOL:
		check(got == expected, "%s: got %s expected %s" % [label, str(got), str(expected)])
	elif typeof(expected) == TYPE_STRING:
		check(String(got) == String(expected), "%s: got %s expected %s" % [label, str(got), str(expected)])
	else:
		check(_near(got, expected), "%s: got %s expected %s" % [label, str(got), str(expected)])

func _init() -> void:
	_reg = load("res://src/autoload/data_registry.gd").new()
	_reg.reload_all()
	test_data_loads()
	if _reg.load_errors.is_empty():
		_d = _reg.bundle()
		var f := FileAccess.open("res://tests/vectors/cases.json", FileAccess.READ)
		check(f != null, "vectors file readable")
		if f != null:
			_vec = JSON.parse_string(f.get_as_text())
		test_character_identity_and_equal_hp()
		test_skill_data_consistency()
		test_loadout_combinations()
		test_vectors_stats()
		test_vectors_scenarios()
		test_vectors_loadouts()
		test_vectors_authority()
		test_vectors_haptics()
		test_vectors_hud()
		test_skills_change_pipeline_results()
		test_profile_migration_and_defaults()
		test_loadout_presets()
		test_controls_persistence()
		test_haptic_sanitize()
	test_save_roundtrip()
	test_save_backup_recovery()
	test_save_tamper_detected()
	test_settings_defaults_and_validation()
	test_settings_persistence()
	print("tests: %d passed, %d failed" % [_passes, _fails])
	quit(1 if _fails > 0 else 0)

# ------------------------------------------------------------------ data
func test_data_loads() -> void:
	check(_reg.load_errors.is_empty(), "data load errors: %s" % [_reg.load_errors])
	check(_reg.count("characters") >= 2, "need >= 2 characters")
	check(_reg.count("maps") == 5, "need 5 maps in data")

func test_character_identity_and_equal_hp() -> void:
	var allowed := ["id", "name", "role", "theme", "personality", "palette", "suggested_preset"]
	var hp_values: Dictionary = {}
	for id in _d["characters"]:
		var c: Dictionary = _d["characters"][id]
		for k in c:
			check(allowed.has(k), "character %s has gameplay key '%s' (characters must be identity-only)" % [id, k])
		var lo: Dictionary = LoadoutData.default_loadout(_d)
		lo["character"] = id
		var st: Dictionary = Combatant.from_loadout(_d, lo)
		hp_values[float(st["max_hp"])] = true
		check(_near(st["max_hp"], _d["rules"]["base_hp"]), "%s max HP equals base HP" % id)
		check(_near(st["ep"], _d["rules"]["base_ep"]), "%s starts with base EP" % id)
	check(hp_values.size() == 1, "every character has the same base HP")
	check(_d["characters"].size() >= 2, "at least 2 characters")

func test_skill_data_consistency() -> void:
	var skills: Dictionary = _d["skills"]
	var actives: int = 0
	var passives: int = 0
	for id in skills:
		var s: Dictionary = skills[id]
		check(["active", "passive", "pet"].has(String(s["kind"])), "%s has valid kind" % id)
		if String(s["kind"]) == "active":
			actives += 1
		if String(s["kind"]) == "passive":
			passives += 1
			check(int(s["cost"]) >= 1 and int(s["cost"]) <= 3, "%s cost 1..3" % id)
		else:
			check(s.has("cooldown") and s.has("ep_cost"), "%s has cooldown and ep_cost" % id)
		for e in s.get("effects", []):
			check(_d["rules"]["stat_defaults"].has(String(e["stat"])), "%s effect stat %s is known" % [id, e["stat"]])
		for ex in s.get("excludes", []):
			check(skills.has(String(ex)) and (skills[String(ex)].get("excludes", []) as Array).has(id), "%s exclusion with %s is symmetric" % [id, ex])
	check(actives >= 4 and passives >= 8, "skill pool large enough to build from (%d active, %d passive)" % [actives, passives])
	for pid in _d["pets"]:
		check(String(_d["skills"][String(_d["pets"][pid]["skill"])]["kind"]) == "pet", "pet %s ability is a pet skill" % pid)

func test_loadout_combinations() -> void:
	var base: Dictionary = LoadoutData.default_loadout(_d)
	check(Validator.validate(_d, base).is_empty(), "default loadout valid")
	for p in _d["presets"]:
		check(Validator.validate(_d, p["loadout"]).is_empty(), "built-in preset %s valid" % p["id"])
	for cid in _d["characters"]:
		for pid in _d["pets"]:
			var lo: Dictionary = LoadoutData.with_slot(LoadoutData.with_slot(base, "character", 0, cid), "pet", 0, pid)
			check(Validator.validate(_d, lo).is_empty(), "character %s can use pet %s" % [cid, pid])
	for sid in _d["skills"]:
		var s: Dictionary = _d["skills"][sid]
		if String(s["kind"]) == "active":
			check(Validator.validate(_d, LoadoutData.with_slot(base, "active", 0, sid)).is_empty(), "active %s equippable" % sid)
		elif String(s["kind"]) == "passive":
			var empty: Dictionary = LoadoutData.with_slot(base, "passive", 0, sid)
			for i in range(1, 4):
				empty = LoadoutData.with_slot(empty, "passive", i, "")
			check(Validator.validate(_d, empty).is_empty(), "passive %s equippable alone" % sid)
	check(Validator.validate(_d, LoadoutData.with_slot(base, "active", 0, "quick_hands")).has("E_ACTIVE"), "passive cannot go in active slot")

# ------------------------------------------------------------------ vectors
func test_vectors_stats() -> void:
	for c in _vec["stats"]:
		var out: Dictionary = StatResolver.resolve(_d["rules"], c["mods"])
		for k in c["expect"]:
			_same(out[k], c["expect"][k], "stats/%s/%s" % [c["name"], k])

func _obs(st: Dictionary) -> Dictionary:
	return {"hp": st["hp"], "max_hp": st["max_hp"], "ep": st["ep"], "helmet_dur": st["helmet"]["dur"], "vest_dur": st["vest"]["dur"],
		"shield": st["shield"], "alive": st["alive"], "downed": st["downed"], "using": st["using"] != null,
		"hots": (st["hots"] as Array).size(), "health_kit": int((st["inventory"] as Dictionary).get("health_kit", 0))}

func _run(sc: Dictionary) -> Dictionary:
	var st: Dictionary = Combatant.make(_d, sc["init"])
	var last: Dictionary = {}
	for s in sc["steps"]:
		var op: String = String(s["op"])
		var now: float = float(s.get("now", 0.0))
		if op == "hit":
			var r: Dictionary = DamagePipeline.apply_hit(_d, st, s["hit"], now)
			st = r["state"]
			last = r["report"]
		elif op == "tick":
			st = Vitals.tick(_d, st, float(s["dt"]), now)
			last = {}
		elif op == "item":
			var r2: Dictionary = Vitals.item_start(_d, st, String(s["id"]), now)
			st = r2["state"]
			last = {"err": r2["err"]}
		elif op == "skill":
			var r3: Dictionary = SkillExec.activate(_d, st, String(s["id"]), now)
			st = r3["state"]
			last = {"err": r3["err"]}
	return {"state": st, "last": last}

func test_vectors_scenarios() -> void:
	for sc in _vec["scenarios"]:
		var res: Dictionary = _run(sc)
		var got: Dictionary = _obs(res["state"])
		for k in sc["expect"]:
			_same(got[k], sc["expect"][k], "scenario/%s/%s" % [sc["name"], k])
		for k in sc["last"]:
			_same(res["last"].get(k), sc["last"][k], "scenario/%s/last.%s" % [sc["name"], k])

func test_vectors_loadouts() -> void:
	for c in _vec["loadouts"]:
		var got: Array = Validator.validate(_d, c["loadout"])
		check(got == c["expect_codes"], "loadout/%s: got %s expected %s" % [c["name"], str(got), str(c["expect_codes"])])

func test_vectors_authority() -> void:
	for c in _vec["authority"]:
		var r: Dictionary = Authority.admit(_d, c["claimed"])
		check(bool(r["ok"]) == bool(c["expect_ok"]), "authority/%s ok flag" % c["name"])
		check(r["errors"] == c["expect_codes"], "authority/%s codes got %s" % [c["name"], str(r["errors"])])
		var st: Dictionary = Authority.make_combatant(_d, r["loadout"])
		check(_near(st["max_hp"], _d["rules"]["base_hp"]), "authority/%s combatant HP comes from rules, not the claim" % c["name"])
		check(_near(st["ep"], _d["rules"]["base_ep"]), "authority/%s combatant EP comes from rules" % c["name"])
		check((st["passive_mods"] as Array).size() <= 4, "authority/%s at most 4 passives applied" % c["name"])

func test_vectors_haptics() -> void:
	for c in _vec["haptics"]:
		var r: Dictionary = HapticConfig.resolve(_d, c["cfg"], String(c["control"]))
		_same(r["fire"], c["expect"]["fire"], "haptics/%s fire" % c["name"])
		if bool(c["expect"]["fire"]):
			_same(r["duration_ms"], c["expect"]["duration_ms"], "haptics/%s duration" % c["name"])
			_same(r["amplitude"], c["expect"]["amplitude"], "haptics/%s amplitude" % c["name"])

func _pair_set(pairs: Array) -> Dictionary:
	var out: Dictionary = {}
	for p in pairs:
		var a: String = String(p[0])
		var b: String = String(p[1])
		out[a + "|" + b if a < b else b + "|" + a] = true
	return out

func test_vectors_hud() -> void:
	for c in _vec["hud"]:
		var scr := Vector2(float(c["screen"][0]), float(c["screen"][1]))
		var got: Dictionary = HudLayout.sanitize(_d, c["layout"], scr, c["insets"])
		for cid in c["expect"]:
			for k in c["expect"][cid]:
				_same(got[cid][k], c["expect"][cid][k], "hud/%s/%s.%s" % [c["name"], cid, k])
		var ov: Dictionary = _pair_set(HudLayout.overlaps(_d, got, scr))
		var ev: Dictionary = _pair_set(c["overlaps"])
		check(ov.keys().size() == ev.keys().size(), "hud/%s overlap count" % c["name"])
		for k in ev:
			check(ov.has(k), "hud/%s expects overlap %s" % [c["name"], k])
	for pname in _vec["hud_presets"]:
		var lay: Dictionary = HudLayout.preset(_d, String(pname))
		for cid in _vec["hud_presets"][pname]:
			for k in _vec["hud_presets"][pname][cid]:
				_same(lay[cid][k], _vec["hud_presets"][pname][cid][k], "hud preset %s/%s.%s" % [pname, cid, k])

# ------------------------------------------------------------------ gameplay effects of skills (data-driven)
func _body_hit(passives: Array, zone: String, vest: int = 0, helmet: int = 0) -> Dictionary:
	var st: Dictionary = Combatant.make(_d, {"passives": passives, "vest": [vest], "helmet": [helmet]})
	return DamagePipeline.apply_hit(_d, st, {"damage": 14.0, "zone": zone, "head_mult": 2.0}, 0.0)["report"]

func test_skills_change_pipeline_results() -> void:
	var base: Dictionary = _body_hit([], "head")
	check(float(_body_hit(["hardened_helm"], "head")["hp_damage"]) < float(base["hp_damage"]), "Hardened Helm reduces headshot damage")
	check(float(_body_hit(["combat_conditioning"], "body")["hp_damage"]) < float(_body_hit([], "body")["hp_damage"]), "Combat Conditioning reduces damage")
	var plain: Dictionary = Combatant.make(_d, {"passives": [], "vest": [3]})
	var plated: Dictionary = Combatant.make(_d, {"passives": ["reinforced_plating"], "vest": [3]})
	var h := {"damage": 20.0, "zone": "body"}
	var a: Dictionary = DamagePipeline.apply_hit(_d, plain, h, 0.0)["state"]
	var b: Dictionary = DamagePipeline.apply_hit(_d, plated, h, 0.0)["state"]
	check(float(b["vest"]["dur"]) > float(a["vest"]["dur"]), "Reinforced Plating saves vest durability")
	var more_ep: Dictionary = Combatant.make(_d, {"passives": ["capacitor_bank"]})
	check(_near(Vitals.max_ep(_d, more_ep, 0.0), float(_d["rules"]["base_ep"]) + 25.0), "Capacitor Bank raises max EP by 25")
	check(_near(Vitals.max_ep(_d, Combatant.make(_d, {}), 0.0), _d["rules"]["base_ep"]), "max EP default")
	var slow: Dictionary = Combatant.make(_d, {"hp": 100.0})
	var fast: Dictionary = Combatant.make(_d, {"hp": 100.0, "passives": ["quick_hands"]})
	var fa: float = float(Vitals.item_start(_d, slow, "health_kit", 0.0)["state"]["using"]["finish_at"])
	var fb: float = float(Vitals.item_start(_d, fast, "health_kit", 0.0)["state"]["using"]["finish_at"])
	check(fb < fa, "Quick Hands shortens item apply time")
	var tight: Dictionary = StatResolver.resolve(_d["rules"], [{"stat": "damage_taken_mult", "op": "mult", "value": 0.1}])
	check(_near(tight["damage_taken_mult"], 0.6), "damage reduction cannot exceed the cap")

# ------------------------------------------------------------------ profile / presets / controls
func test_profile_migration_and_defaults() -> void:
	check(ProfileData.default_loadout() == LoadoutData.default_loadout(_d), "ProfileData default loadout equals first built-in preset")
	var old := {"selected_character": "kade", "selected_pet": "talon", "xp": 12.0,
		"loadout": {"primary": "vanguard_ar", "secondary": "peacekeeper_pistol", "throwable": "veil", "backpack_level": 1}, "custom": "keep"}
	var m: Dictionary = ProfileData.migrate(old, 1)
	check(not m.has("selected_character") and not m.has("selected_pet"), "v1 selection keys removed")
	check(m["loadout"]["character"] == "kade" and m["loadout"]["pet"] == "talon", "v1 character and pet carried into loadout")
	check(m["loadout"]["primary"] == "vanguard_ar" and m["loadout"]["throwable"] == "veil", "v1 weapons carried over")
	check(typeof(m["xp"]) == TYPE_INT and m["xp"] == 12 and m["custom"] == "keep", "xp coerced, unknown keys preserved")
	var lo: Dictionary = LoadoutData.normalize(m["loadout"])
	check(Validator.validate(_d, lo).is_empty(), "migrated v1 loadout is valid")
	check((lo["passives"] as Array).size() == 4, "passives padded to 4")
	var fresh: Dictionary = ProfileData.migrate({}, 2)
	check(fresh.has("loadout") and fresh.has("presets"), "missing keys filled")
	var json_round: Dictionary = JSON.parse_string(JSON.stringify(ProfileData.defaults()))
	check(Validator.validate(_d, LoadoutData.normalize(json_round["loadout"])).is_empty(), "default loadout survives JSON round-trip (int/float)")

func test_loadout_presets() -> void:
	var lo: Dictionary = LoadoutData.default_loadout(_d)
	var r: Dictionary = LoadoutData.save_preset(_d, [], "  My Build  ", lo)
	check(bool(r["ok"]) and r["presets"][0]["name"] == "My Build", "preset saved with trimmed name")
	var bad: Dictionary = LoadoutData.with_slot(lo, "passive", 1, "iron_knuckles")
	var rb: Dictionary = LoadoutData.save_preset(_d, r["presets"], "Illegal", bad)
	check(not bool(rb["ok"]) and (r["presets"] as Array).size() == 1 and (rb["presets"] as Array).size() == 1, "invalid loadout is NOT saved as preset")
	var r2: Dictionary = LoadoutData.save_preset(_d, r["presets"], "my build", LoadoutData.with_slot(lo, "pet", 0, "pip"))
	check(bool(r2["ok"]) and (r2["presets"] as Array).size() == 1 and r2["presets"][0]["loadout"]["pet"] == "pip", "same name (case-insensitive) overwrites")
	check(not bool(LoadoutData.save_preset(_d, [], "   ", lo)["ok"]), "empty preset name rejected")
	var many: Array = []
	for i in int(_d["rules"]["loadout"]["max_custom_presets"]):
		many = LoadoutData.save_preset(_d, many, "P%d" % i, lo)["presets"]
	check(many.size() == int(_d["rules"]["loadout"]["max_custom_presets"]), "preset limit reached")
	check(not bool(LoadoutData.save_preset(_d, many, "One more", lo)["ok"]), "preset limit enforced")
	check(LoadoutData.delete_preset(many, "p0").size() == many.size() - 1, "preset deleted")
	check(LoadoutData.clean_name("a\u0001b\u007fc" + "x".repeat(40), 16).length() <= 16, "name cleaned and truncated")
	var stored: Array = [{"name": "ok", "loadout": lo}, {"name": "broken", "loadout": bad}, "junk", {"name": 5}]
	check(LoadoutData.sanitize_presets(_d, stored).size() == 1, "invalid stored presets dropped on load")
	var wl: Dictionary = LoadoutData.whitelist({"character": "rook", "hp": 9999, "ep": 1e9, "damage_mult": 50})
	check(wl.keys() == ["character"], "whitelist drops stat keys")

func test_controls_persistence() -> void:
	var path := "user://_t_controls.json"
	SaveIO.remove_all(path)
	var data: Dictionary = ControlsData.defaults(_d)
	data["hud"]["fire"]["x"] = 0.5
	data["hud"]["fire"]["scale"] = 1.3
	data["hud"]["fire"]["opacity"] = 0.4
	data["hud"]["pet"]["visible"] = false
	data["layout_preset"] = "custom"
	data["haptics"]["master_intensity"] = 0.5
	data["haptics"]["controls"]["fire"] = {"enabled": true, "preset": "custom", "intensity": 0.9, "duration_ms": 45}
	data["haptics"]["controls"]["jump"] = HapticConfig.make_control(_d, "off")
	check(SaveIO.write(path, data, ControlsData.SCHEMA), "controls saved")
	var r: Dictionary = SaveIO.read(path)
	check(r["source"] == "main", "controls read back")
	var back: Dictionary = ControlsData.migrate(_d, r["data"], int(r["version"]))
	var scr := Vector2(2400, 1080)
	var hud: Dictionary = HudLayout.sanitize(_d, back["hud"], scr)
	check(_near(hud["fire"]["x"], 0.5) and _near(hud["fire"]["scale"], 1.3) and _near(hud["fire"]["opacity"], 0.4), "HUD position/size/opacity persisted")
	check(hud["pet"]["visible"] == false and hud["move"]["visible"] == true, "HUD visibility persisted (required stays visible)")
	check(back["layout_preset"] == "custom", "layout preset persisted")
	check(_near(back["haptics"]["master_intensity"], 0.5), "master haptic intensity persisted")
	check(_near(back["haptics"]["controls"]["fire"]["intensity"], 0.9) and int(back["haptics"]["controls"]["fire"]["duration_ms"]) == 45, "per-control intensity/duration persisted")
	check(back["haptics"]["controls"]["jump"]["enabled"] == false, "per-control off persisted")
	var r2: Dictionary = HapticConfig.resolve(_d, back["haptics"], "fire")
	check(bool(r2["fire"]) and _near(r2["amplitude"], 0.45) and int(r2["duration_ms"]) == 45, "persisted haptic config resolves (0.9 x master 0.5)")
	check(not bool(HapticConfig.resolve(_d, back["haptics"], "jump")["fire"]), "persisted off control does not vibrate")
	SaveIO.remove_all(path)
	var junk: Dictionary = ControlsData.migrate(_d, {"hud": "x", "haptics": 5, "layout_preset": 3}, 1)
	check(junk["layout_preset"] == "default" and junk["haptics"]["controls"].has("fire"), "garbage controls file falls back to defaults")

func test_haptic_sanitize() -> void:
	var cfg: Dictionary = HapticConfig.default_config(_d)
	cfg["master_intensity"] = 7.0
	cfg["controls"]["fire"]["duration_ms"] = 99999
	cfg["controls"]["fire"]["intensity"] = -3
	cfg["controls"]["laser"] = {"enabled": true}
	var s: Dictionary = HapticConfig.sanitize(_d, cfg)
	check(_near(s["master_intensity"], 1.0), "master intensity clamped")
	check(int(s["controls"]["fire"]["duration_ms"]) <= 200 and float(s["controls"]["fire"]["intensity"]) >= 0.0, "control values clamped")
	check(not (s["controls"] as Dictionary).has("laser"), "unknown control dropped")
	var p: Dictionary = HapticConfig.with_preset(_d, HapticConfig.default_config(_d), "fire", "high")
	check(_near(p["controls"]["fire"]["intensity"], 1.0) and int(p["controls"]["fire"]["duration_ms"]) == 60, "preset High applied")
	var off: Dictionary = HapticConfig.with_preset(_d, p, "fire", "off")
	check(not bool(HapticConfig.resolve(_d, off, "fire")["fire"]), "preset Off silences control")

# ------------------------------------------------------------------ save / settings
func test_save_roundtrip() -> void:
	var path := "user://_t_profile.json"
	SaveIO.remove_all(path)
	check(SaveIO.write(path, {"name": "A", "n": 5, "list": [1, 2]}, 1), "write succeeds")
	var r: Dictionary = SaveIO.read(path)
	check(r["source"] == "main", "read from main")
	check(r["data"]["name"] == "A" and int(r["data"]["n"]) == 5, "roundtrip values")
	check(int(r["version"]) == 1, "schema version kept")
	SaveIO.remove_all(path)
	check(SaveIO.read(path)["source"] == "none", "missing file -> none")

func test_save_backup_recovery() -> void:
	var path := "user://_t_profile2.json"
	SaveIO.remove_all(path)
	SaveIO.write(path, {"gen": 1}, 1)
	SaveIO.write(path, {"gen": 2}, 1)
	check(int(SaveIO.read(path)["data"]["gen"]) == 2, "latest generation read")
	var f := FileAccess.open(path, FileAccess.WRITE)
	f.store_string("garbage{{{")
	f.close()
	var r: Dictionary = SaveIO.read(path)
	check(r["source"] == "backup" and int(r["data"]["gen"]) == 1, "corrupt main -> previous generation from backup")
	var f2 := FileAccess.open(path + ".bak", FileAccess.WRITE)
	f2.store_string("also garbage")
	f2.close()
	check(SaveIO.read(path)["source"] == "none", "both corrupt -> none (defaults)")
	SaveIO.remove_all(path)

func test_save_tamper_detected() -> void:
	var path := "user://_t_profile3.json"
	SaveIO.remove_all(path)
	SaveIO.write(path, {"xp": 10}, 1)
	var f := FileAccess.open(path, FileAccess.READ)
	var txt: String = f.get_as_text()
	f.close()
	var parsed: Dictionary = JSON.parse_string(txt)
	parsed["body"] = String(parsed["body"]).replace("10", "99")
	var w := FileAccess.open(path, FileAccess.WRITE)
	w.store_string(JSON.stringify(parsed))
	w.close()
	check(SaveIO.read(path)["source"] == "none", "edited body fails integrity check")
	SaveIO.remove_all(path)

func test_settings_defaults_and_validation() -> void:
	var s := SettingsStore.new()
	check(float(s.get_value("music_volume")) == 0.8, "default music volume")
	check(s.set_value("music_volume", 5.0) and float(s.get_value("music_volume")) == 1.0, "volume clamped to 1.0")
	check(s.set_value("music_volume", -1) and float(s.get_value("music_volume")) == 0.0, "volume clamped to 0.0")
	check(not s.set_value("no_such_key", 1), "unknown key rejected")
	check(not s.set_value("vibration", true), "old vibration key no longer exists (haptics moved to controls.json)")
	check(not s.set_value("fps_limit", 45), "fps 45 rejected")
	check(s.set_value("fps_limit", 90) and int(s.get_value("fps_limit")) == 90, "fps 90 accepted")
	check(not s.set_value("battery_mode", "yes"), "wrong type rejected")
	check(not s.set_value("sensitivity", NAN), "NaN rejected")
	check(not s.set_value("language", "xx"), "unknown language rejected")
	check(s.set_value("sensitivity", 9.0) and float(s.get_value("sensitivity")) == 2.0, "sensitivity clamped")

func test_settings_persistence() -> void:
	var path := "user://_t_settings.cfg"
	var s := SettingsStore.new()
	s.set_value("sfx_volume", 0.3)
	s.set_value("battery_mode", true)
	s.set_value("fps_limit", 30)
	check(s.save_to(path), "settings save")
	var s2 := SettingsStore.new()
	check(s2.load_from(path), "settings load")
	check(is_equal_approx(float(s2.get_value("sfx_volume")), 0.3), "sfx persisted")
	check(bool(s2.get_value("battery_mode")) == true and int(s2.get_value("fps_limit")) == 30, "bool/int persisted")
	var cfg := ConfigFile.new()
	cfg.set_value("settings", "fps_limit", 45)
	cfg.set_value("settings", "music_volume", 7.0)
	cfg.save(path)
	var s3 := SettingsStore.new()
	s3.load_from(path)
	check(int(s3.get_value("fps_limit")) == 60, "invalid stored fps ignored -> default")
	check(float(s3.get_value("music_volume")) == 1.0, "out-of-range stored volume clamped")
	DirAccess.remove_absolute(ProjectSettings.globalize_path(path))
